/**
 * Writes the named accents into src/styles/app.css.
 *
 * Each preset is its hex value run through the same recipe as a custom colour
 * (src/domain/accent.ts), so a named accent and a picked one that share a hex
 * code are the same family. Red, the default, stays written by hand.
 *
 *   node scripts/make-accents.mjs
 *
 * Needs a Node that runs TypeScript files directly (22.6 and later).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { accentFamily } from '../src/domain/accent.ts';

/** id → the colour of the v2 palette. The ids are stored in settings: never rename one. */
const PRESETS = {
  orange: '#e0701f',
  amber: '#d9a200',
  green: '#4c8631',
  teal: '#008c8c',
  blue: '#246fe0',
  indigo: '#4b5bd6',
  purple: '#7656bb',
  pink: '#c2418f',
  cocoa: '#8a5a44',
  graphite: '#2b2f3a',
};

/** Fills that are the colour itself, not the darkened one the recipe would solve
 *  for white glyphs. Sunflower carries dark glyphs instead (v2.css), the only
 *  way a yellow can be a yellow and stay readable. */
const FILL = { orange: '#e8731c', amber: '#f2b705' };

const declarations = (family) => [
  ['accent', 'accent-dark'],
  ['accent-soft', 'accent-tint', 'accent-line'],
  ['accent-wash', 'accent-wash-deep', 'accent-badge'],
  ['sidebar', 'tb-on-line'],
  ['today-line', 'today-wash'],
].map((tokens) => `  ${tokens.map((t) => `--${t}:${family[t]};`).join(' ')}`).join('\n');

const withFill = (id, family) => (FILL[id] ? { ...family, accent: FILL[id] } : family);

const blocks = Object.entries(PRESETS).map(([id, hex]) => `/* ${id}: ${hex} */
:root[data-accent="${id}"],
[data-accent="${id}"]:not(:root){
${declarations(withFill(id, accentFamily(hex, 'light')))}
}
:root[data-accent="${id}"][data-theme="dark"],
[data-theme="dark"] [data-accent="${id}"]:not(:root){
${declarations(withFill(id, accentFamily(hex, 'dark')))}
}`).join('\n');

const file = new URL('../src/styles/app.css', import.meta.url);
const css = readFileSync(file, 'utf8');
const begin = '/* accents:begin (generated by scripts/make-accents.mjs) */';
const end = '/* accents:end */';
const generated = `${begin}\n${blocks}\n${end}`;

let next;
if (css.includes(begin)) {
  next = css.replace(new RegExp(`${begin.replace(/[()*/.]/g, '\\$&')}[\\s\\S]*?${end.replace(/[*/]/g, '\\$&')}`), generated);
} else {
  const from = css.indexOf(':root[data-accent="orange"],');
  const to = css.indexOf('*{box-sizing:border-box}');
  if (from < 0 || to < 0) throw new Error('accent region not found in app.css');
  next = `${css.slice(0, from)}${generated}\n\n${css.slice(to)}`;
}
writeFileSync(file, next);
console.log(`wrote ${Object.keys(PRESETS).length} accents`);
